/**
 * Seeds the demo workspace with a mix of curated and synthetic articles,
 * chunks them, and embeds every chunk so Vector Search has data to work with.
 *
 * Defaults to 50 articles total: the 6 hand-crafted ones below plus 44
 * synthetic ones (varied topics × technologies × angles) generated by
 * generators.js. Tune with --count.
 *
 * Run:
 *   npm run seed                    # 50 articles
 *   npm run seed -- --count=120     # 6 curated + 114 synthetic
 *   npm run seed -- --count=6       # just the curated 6
 *
 * Idempotent: re-running drops the demo workspace and re-creates it.
 *
 * For 1k+ articles, prefer `npm run seed-bulk` — it's the same pipeline
 * with progress reporting and a different default workspace.
 */
import "dotenv/config";
import { Collections, connectDB, closeDB, getDB } from "../src/db.js";
import { embed } from "../src/voyage.js";
import { chunkText } from "../src/utils/chunker.js";
import { buildArticle } from "./generators.js";

const DEMO_SLUG = "demo";
const DEFAULT_COUNT = 50;
const EMBED_BATCH = 96;     // Voyage allows up to 128 inputs/call
const EMBED_CONCURRENCY = 4;

function parseCount() {
  for (const raw of process.argv.slice(2)) {
    const [k, v] = raw.replace(/^--/, "").split("=");
    if (k === "count") return Math.max(1, parseInt(v, 10) || DEFAULT_COUNT);
  }
  return DEFAULT_COUNT;
}

/** Runs `fn(item)` for each item with up to `concurrency` calls in flight. */
async function parallelMap(items, concurrency, fn) {
  let cursor = 0;
  async function worker() {
    while (cursor < items.length) {
      const idx = cursor++;
      await fn(items[idx], idx);
    }
  }
  await Promise.all(
    Array.from({ length: Math.min(concurrency, items.length) }, worker),
  );
}

const ARTICLES = [
  {
    title: "Getting started with MongoDB Atlas Vector Search",
    summary:
      "How to enable vector search on an Atlas cluster and run your first $vectorSearch query.",
    tags: ["mongodb", "atlas", "vector-search", "tutorial"],
    category: "tutorial",
    content: `## What it is

MongoDB Atlas Vector Search lets you store embeddings alongside the
documents they describe and query them with the $vectorSearch aggregation
stage. There is no separate vector database to operate.

## Setting it up

Create an Atlas cluster on M10 or higher (the shared free tier also works
today). Define a vector search index that points at the field holding your
embeddings, choose a similarity metric (cosine, dot product, or euclidean),
and the dimension count (1024 for voyage-3).

## Running a query

Issue a $vectorSearch query with a query vector and the stage returns the
documents whose embeddings are closest under the similarity metric. Tune
\`numCandidates\` (recall) and \`limit\` (latency) to your workload.

## The chunking pattern

A common pattern is to chunk long documents, embed each chunk, store the
chunks in their own collection with a reference back to the parent, and
$lookup the parent document at query time. That keeps the operational
collection small while letting semantic search work at paragraph
granularity.`,
  },
  {
    title: "Atlas Search vs. Vector Search: when to use which",
    summary:
      "A practical comparison of keyword search and semantic search on MongoDB Atlas.",
    tags: ["mongodb", "atlas", "search", "vector-search"],
    category: "guide",
    content: `## Atlas Search (keyword)

Atlas Search is built on Apache Lucene and gives you classic full-text
retrieval: BM25 scoring, language analyzers, autocomplete, fuzzy matching,
faceting, and highlights. It excels when the user knows the keywords they
are looking for.

## Atlas Vector Search (semantic)

Atlas Vector Search returns documents whose embeddings are closest to a
query embedding. It excels when the user describes what they want in
natural language and the wording differs from what is in the corpus —
synonyms, paraphrases, multilingual queries.

## Hybrid in practice

In practice, hybrid search wins. Run both, fuse the rankings with
Reciprocal Rank Fusion, and you get the recall of semantic search with the
precision of keyword search. MongoDB 8.1 added $rankFusion as a single
aggregation stage to do exactly this.`,
  },
  {
    title: "Designing a chunking strategy for RAG",
    summary:
      "Picking chunk size, overlap, and boundaries when feeding documents to an embedding model.",
    tags: ["rag", "embeddings", "chunking"],
    category: "guide",
    content: `## Why chunking matters

Chunking is the unglamorous step that decides how good your retrieval
feels. Chunks that are too large dilute the embedding — a single vector
cannot represent five unrelated paragraphs. Chunks that are too small lose
context — the embedding describes a fragment with no surroundings.

## Reasonable defaults

A starting point is 500–1500 characters per chunk. Break on natural
boundaries (paragraph, sentence) rather than fixed character counts. For
technical documentation with code blocks, prefer larger chunks so the code
stays together.

## Semantic chunking by section

The most precise approach for structured docs (Markdown, AsciiDoc) is to
chunk by heading: every \`##\` or \`###\` section becomes one chunk,
prefixed with the breadcrumb path. Now the embedding represents a coherent
topic and retrieval hits return "the section about X", not "characters
800-1600".

## Storage layout

Store one document per chunk in MongoDB with a reference to the parent
article. That way you can answer "which article does this passage come
from?" with a single $lookup, and re-indexing a single article is just a
deleteMany + insertMany on its chunks.`,
  },
  {
    title: "Reciprocal Rank Fusion explained",
    summary:
      "Why RRF is the default way to combine multiple ranked lists in hybrid search.",
    tags: ["search", "rrf", "hybrid"],
    category: "concept",
    content: `## The formula

Reciprocal Rank Fusion combines several ranked result lists into a single
ranking. For each document and each ranker, it adds 1 / (k + rank) to the
document's score, where k is a damping constant (60 is the value from the
original paper). Documents that appear near the top of multiple rankers
get the highest fused score.

## Why not just sum the scores?

RRF is popular for hybrid keyword + vector search because the two rankers
produce scores on completely different scales: Atlas Search returns
BM25-style scores that can climb into the tens, while Vector Search
returns cosine similarities between 0 and 1. Trying to normalise and add
them is fragile. RRF only looks at rank position, so the scale problem
disappears entirely.

## Trade-offs

The trade-off is that RRF discards score magnitude — a document that is
slightly ahead in one ranker counts the same as one that is far ahead.
For most applications this is a feature, not a bug: it makes the algorithm
robust to outlier scores and easy to reason about.`,
  },
  {
    title: "Voyage AI embeddings overview",
    summary:
      "Models, dimensions, and input types offered by Voyage AI for embeddings and reranking.",
    tags: ["voyage-ai", "embeddings", "rerank"],
    category: "reference",
    content: `## Embedding models

Voyage AI provides general-purpose and domain-specific embedding models.
voyage-3 returns 1024-dimensional vectors and is a solid default for
English technical content. voyage-3-large doubles the parameters for
slightly higher quality.

## The input_type parameter

Every embedding call accepts an \`input_type\` of either \`"document"\` or
\`"query"\`. The same text passed with different input types produces
different vectors — using the right one measurably improves retrieval
quality. Use \`"document"\` when embedding chunks for storage and
\`"query"\` when embedding a user's search query.

## Reranking with rerank-2

For reranking, Voyage offers the rerank-2 model. A typical pipeline does
a coarse retrieval with Vector Search (say, the top 50 chunks), passes
those candidates plus the query to the reranker, and keeps the top 5–10
after reranking. The reranker is more expensive per pair than the
embedding model, so you only call it on the shortlist.

## Calling via MongoDB

After MongoDB acquired Voyage AI, the same models are exposed at
\`https://ai.mongodb.com/v1\` using an Atlas Model API Key (prefix \`al-\`).
Billing flows through your Atlas org instead of a separate Voyage account.`,
  },
  {
    title: "Why store embeddings in MongoDB",
    summary:
      "The case for a single database for operational data and vectors.",
    tags: ["mongodb", "architecture", "vector-database"],
    category: "opinion",
    content: `## The cost of a second store

Running a separate vector database means a second store to provision,
monitor, secure, and keep in sync with your primary database. For most
applications, the gain in raw query latency is dwarfed by the cost of
consistency: when a document changes, its embedding must change too, and
the two systems can drift.

## Co-location wins

Storing embeddings in MongoDB removes that class of problem. Your
permissions live next to the vector. Your tags filter the same way at
$match time as they do inside $vectorSearch via the filter field. You
can update an article and re-index its chunks in a single transaction.

## Operational simplicity

Atlas Vector Search scales horizontally with your cluster, so you do not
pay a "single database" penalty for staying simple. One backup policy, one
network config, one access manager, one query language. The same
aggregation pipeline that filters articles by tag can sort them by vector
similarity — no impedance mismatch between operational and search layers.`,
  },
];

async function main() {
  const db = await connectDB();

  console.log("→ cleaning previous demo data");

  const oldWs = await db
    .collection(Collections.workspaces)
    .findOne({ slug: DEMO_SLUG });

  if (oldWs) {
    await db
      .collection(Collections.articles)
      .deleteMany({ workspaceId: oldWs._id });
    await db
      .collection(Collections.chunks)
      .deleteMany({ workspaceId: oldWs._id });
    await db
      .collection(Collections.workspaces)
      .deleteOne({ _id: oldWs._id });
  }

  console.log("→ creating demo user + workspace");

  const userRes = await db.collection(Collections.users).findOneAndUpdate(
    { email: "demo@knowledge-base.dev" },
    {
      $setOnInsert: {
        email: "demo@knowledge-base.dev",
        name: "Demo User",
        createdAt: new Date(),
      },
    },
    { upsert: true, returnDocument: "after" },
  );
  const user = userRes;

  const ws = {
    name: "Demo Workspace",
    slug: DEMO_SLUG,
    ownerId: user._id,
    members: [{ userId: user._id, role: "owner" }],
    createdAt: new Date(),
  };
  const wsInsert = await db.collection(Collections.workspaces).insertOne(ws);
  ws._id = wsInsert.insertedId;

  console.log(`  ✓ workspace ${ws._id} created`);

  // Build the article set: curated first, then synthetic top-up.
  const targetCount = parseCount();
  const curated = ARTICLES.slice(0, Math.min(targetCount, ARTICLES.length));
  const syntheticCount = Math.max(0, targetCount - curated.length);
  const synthetic = Array.from({ length: syntheticCount }, (_, i) =>
    buildArticle(i, 7),
  );
  const allDrafts = [...curated, ...synthetic];

  console.log(
    `→ inserting ${allDrafts.length} articles (${curated.length} curated + ${synthetic.length} synthetic)`,
  );

  // 1. Insert all article docs in one go.
  const articleDocs = allDrafts.map((a) => ({
    workspaceId: ws._id,
    authorId: user._id,
    title: a.title,
    content: a.content,
    summary: a.summary ?? "",
    tags: a.tags,
    category: a.category,
    visibility: "workspace",
    status: "published",
    createdAt: new Date(),
    updatedAt: new Date(),
  }));

  const insertRes = await db
    .collection(Collections.articles)
    .insertMany(articleDocs, { ordered: false });

  articleDocs.forEach((d, i) => (d._id = insertRes.insertedIds[i]));
  console.log(`  ✓ ${articleDocs.length} articles inserted`);

  // 2. Build chunk records (no embeddings yet).
  const chunkRecords = [];
  for (const art of articleDocs) {
    // Title as H1 so it becomes the breadcrumb root in every chunk.
    const pieces = chunkText(`# ${art.title}\n\n${art.content}`);
    pieces.forEach((text, idx) => {
      chunkRecords.push({
        articleId: art._id,
        workspaceId: ws._id,
        chunkIndex: idx,
        text,
        tags: art.tags,
        category: art.category,
        visibility: art.visibility,
        createdAt: new Date(),
      });
    });
  }
  console.log(`→ chunked into ${chunkRecords.length} pieces`);

  // 3. Embed in parallel batches via Voyage, insert each batch as it returns.
  const batches = [];
  for (let i = 0; i < chunkRecords.length; i += EMBED_BATCH) {
    batches.push({
      start: i,
      end: Math.min(i + EMBED_BATCH, chunkRecords.length),
    });
  }

  console.log(
    `→ embedding ${chunkRecords.length} chunks (batch=${EMBED_BATCH}, concurrency=${EMBED_CONCURRENCY})`,
  );
  const startedAt = Date.now();
  let embedded = 0;

  await parallelMap(batches, EMBED_CONCURRENCY, async (batch) => {
    const slice = chunkRecords.slice(batch.start, batch.end);
    const vectors = await embed(slice.map((c) => c.text), "document");
    slice.forEach((c, k) => (c.embedding = vectors[k]));
    await db.collection(Collections.chunks).insertMany(slice, { ordered: false });

    embedded += slice.length;
    const elapsed = (Date.now() - startedAt) / 1000;
    const rate = embedded / Math.max(elapsed, 0.01);
    process.stdout.write(
      `\r  ${embedded}/${chunkRecords.length} chunks · ${rate.toFixed(1)}/s   `,
    );
  });
  console.log("\n  ✓ chunks embedded + inserted");

  console.log("\n✓ seed complete");
  console.log(`  user:      ${user._id}`);
  console.log(`  workspace: ${ws._id}`);
  console.log(`  articles:  ${articleDocs.length}`);
  console.log(`  chunks:    ${chunkRecords.length}`);

  await closeDB();
}

main().catch((err) => {
  console.error("\n✗ seed failed:", err);
  process.exit(1);
});
